import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const urbanist = Urbanist({
  variable: "--font-Urbanist",
  subsets: ["latin"],
  display: "swap",
});

const gtAmerica = localFont({
  variable: "--font-GTAmerican",
  src: "../../public/fonts/FontsFree-Net-GT-America-Regular-1.ttf",
  display: "swap",
});
const canelaDeck = localFont({
  variable: "--font-CanelaDeck",
  src: "../../public/fonts/CanelaDeck-Medium-Trial.otf",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`   ${urbanist.variable}  ${canelaDeck.variable} ${gtAmerica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}